setup.py: greenlet<=0.4.15 for better compat (pypy)
https://github.com/jgehrcke/gipc/pull/106/checks?check_run_id=1639649867#step:5:48
Found existing installation: greenlet 0.4.13
ERROR: Cannot uninstall 'greenlet'. It is a
distutils installed project and thus we cannot accurately
determine which files belong to it which would lead to
only a partial uninstall.

CHANGELOG: tiny polish